server:

   # =========================
   # Authoritative Zone → BIND
   # =========================
   stub-zone:
     name: "@@domain@@."
     stub-addr: 127.0.0.1@53530
 
   # =========================
   # Reverse Zones → BIND
   # =========================
   stub-zone:
     name: "0.168.192.in-addr.arpa."
     stub-addr: 127.0.0.1@53530
 
   stub-zone:
     name: "2.168.192.in-addr.arpa."
     stub-addr: 127.0.0.1@53530
 
   stub-zone:
     name: "4.168.192.in-addr.arpa."
     stub-addr: 127.0.0.1@53530
 
   stub-zone:
     name: "104.168.192.in-addr.arpa."
     stub-addr: 127.0.0.1@53530
